version: 1.0

images:
  -
    image_name: phpobjecti
    local_port: 80
    timeout: 600
  -
    image_name: yaml-vuln
    local_port: 4567
    timeout: 600
  -
    image_name: projectleaks
    local_port: 5000
    timeout: 600
  -
    image_name: ssti-vuln
    local_port: 9000
    timeout: 600
  -
    image_name: xxe
    local_port: 8000
    timeout: 600
  -
    image_name: lfi
    local_port: 80
    timeout: 60

app_conf:
  port_start: 10001
  port_end: 11000
  app_port: 5000
  host: "http://127.0.0.1"
  debug: False

credentials:
  admin: retrymp3
  user: user
